USE BDSIGELI;

DROP TABLE PRESTAMO;
DROP TABLE USUARIO;
DROP TABLE LIBRO;
DROP TABLE TIPO_LIBRO;
DROP TABLE ESTADO_LIBRO;

CREATE TABLE USUARIO (
COD_USU INT AUTO_INCREMENT,
NOM_USU VARCHAR (50) NOT NULL,
APE_PAT_USU VARCHAR (50) NOT NULL,
APE_MAT_USU VARCHAR (50) NOT NULL,
DNI_USU CHAR (8) NOT NULL,
EDAD_USU INT NOT NULL,
EMAIL_USU VARCHAR (50) NULL,
TEL_USU VARCHAR (20) NULL,
LOG_USU VARCHAR (20) NOT NULL,
CLA_USU VARCHAR (20) NOT NULL,
PRIMARY KEY (COD_USU)
);

ALTER TABLE USUARIO
AUTO_INCREMENT=1001;

CREATE TABLE TIPO_LIBRO (
ID_TIP INT PRIMARY KEY,
DES_TIP VARCHAR (50) NOT NULL
);

CREATE TABLE ESTADO_LIBRO (
ID_EST INT PRIMARY KEY,
DES_EST VARCHAR (50) NOT NULL
);

CREATE TABLE LIBRO (
ID_LIB INT PRIMARY KEY,
NOM_LIB VARCHAR (50) NOT NULL,
DES_LIB VARCHAR(500) NOT NULL,
ID_TIP INT NOT NULL,
ID_EST INT NOT NULL
);

ALTER TABLE LIBRO
ADD FOREIGN KEY (ID_TIP) REFERENCES TIPO_LIBRO (ID_TIP),
ADD FOREIGN KEY (ID_EST) REFERENCES ESTADO_LIBRO (ID_EST);

CREATE TABLE PRESTAMO (
ID_PRES INT AUTO_INCREMENT,
COD_USU INT NOT NULL,
ID_LIB INT NOT NULL,
FEC_PRES DATETIME NOT NULL,
FEC_DEV_PRES DATETIME NOT NULL,
OBS_PRES VARCHAR (500) DEFAULT 'Sin observaciones',
PRIMARY KEY (ID_PRES)
);

ALTER TABLE PRESTAMO
ADD FOREIGN KEY (COD_USU) REFERENCES USUARIO (COD_USU),
ADD FOREIGN KEY (ID_LIB) REFERENCES LIBRO (ID_LIB);